name: segment_analytics
description: Segment.com library for Flutter
version: 1.0.0
homepage: https://www.segment.com
author: Tobias Gottwald <inch4tk@gmail.com>, FaisalAbid <faisal.abid@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  device_info: ^0.4.0+2
  connectivity: ^0.4.4